apiVersion: v1
kind: Service
metadata:
  name: forge-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: forge-api
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: forge-api
  ports:
    - name: rest
      port: {{ .Values.service.port }}
      targetPort: 6066
