apiVersion: v1
kind: ServiceAccount
metadata:
  name: forge-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: forge-api
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
